service: python-service

provider:
  name: openwhisk
  runtime: python

functions:
  match:
    handler: handler.match
    image:  philschmi/matchingRooms
    events:
      - http:
          path: match
          method: get

plugins:
  - serverless-openwhisk